language: cpp
compiler:
- gcc
before_script:
- cppcheck --error-exitcode=1  --enable=warning,performance,portability,style --language=c++
  --quiet src/ examples/ include/
script:
- mkdir build
- cd build
- cmake .. && make
- cd ..
- debuild -b -uc -us
sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libfcgi-dev devscripts debhelper cppcheck
deploy:
  token:
    secure: ZpMbw5WFP0CxB9QYU/zBIjhmAOuiXEf1sGl89oIFoc80nOydCsrwfsJo2TGaXAbE7Nsr3xJZlGOBOnEyRodppeIGatleqYekPiLmE6QdScEbxt9Dsf55EFE6nDQE9bbX/HoAZRRkkPNhMZrRVK9V6gVrhVhknjlVCt2Hp+roDjWIaPnpkZTSigsluKMOjvoGUE88tblkSn2nSlApB4yZPcR/pJQ1lU+btcsjoezoIjW8krYgbZMTrR7k2Gju7VZiQcrmlKPYpUV9f51u9pbSdpdp3iGqpjuS8KQEhVFLuqSpe9U5P8RlZ7Z7IkwSAETmvGx9iNmQI5cQZ3Q2+Dz6jhftwa70W4gCDm40KV0ohNG+/rlTBsw4baVe3TsNzFB/AewOm92f0m8ZqwIIxGzyiG4SnGkX5j/gwS8X8q+bu5oKvrHZUMOGau1YIFyNYzQuumzoK0J+CzJnfJEmRCFaF+1T5frZ0x3TFF/H5DtaWzE/mAJwP9G0sWx96PuxYf5CND0exMA5a2qI2IKIs1hInBcuQ8kbJMi+cGdfjMkgMuyTrvbGP9c49xSQ79TPJaNQNeyOaBNqOebdAyeXsb/yGwCCaTOWwvUS9FMJW8ckKnwaIds0IFW4pYr2mPmppCiiI3O4FUjmPp+Tfj1LZEmRm9G7N9SGVvN0QVBHxicnEPw=
  provider: packagecloud
  repository: stable
  username: crazygoat
  dist: ubuntu/xenial
  skip_cleanup: true
